apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --out kubernetes
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.network/nostream: "true"
    io.kompose.service: nostream
  name: nostream
spec:
  containers:
    - image: ghcr.io/cameri/nostream:main
      name: nostream
      env:
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: nostream-secret-kube
              key: password
        - name: RELAY_PORT
          value: 8008
        # Master
        - name: NOSTR_CONFIG_DIR
          value: /home/node/.nostr
        - name: DB_HOST
          value: nostream-db
        - name: DB_PORT
          value: 5432
        - name: DB_USER
          value: nostr_ts_relay
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nostream-db-password-kube
              key: password
        - name: DB_NAME
          value: nostr_ts_relay
        - name: DB_MIN_POOL_SIZE
          value: 16
        - name: DB_MAX_POOL_SIZE
          value: 64
        - name: DB_ACQUIRE_CONNECTION_TIMEOUT
          value: 60000
        # Read Replica
        - name: READ_REPLICAS
          value: 2
        - name: READ_REPLICA_ENABLED
          value: 'false'
        # Add RR2, RR3, etc. to configure more read replicas
        # Redis
        - name: REDIS_HOST
          value: nostream-cache
        - name: REDIS_PORT
          value: 6379
        - name: REDIS_USER
          value: default
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nostream-cache-password-kube
              key: password
        - name: TOR_HOST
          value: tor_proxy
        - name: TOR_CONTROL_PORT
          value: 9051
        - name: TOR_PASSWORD
          value: nostr_ts_relay
        - name: HIDDEN_SERVICE_PORT
          value: 80
        # Payments Processors
        # Zebedee
        - name: ZEBEDEE_API_KEY
          value: "" 
        # Nodeless.io
        - name: NODELESS_API_KEY
          value: "" 
        - name: NODELESS_WEBHOOK_SECRET
          value: "" 
        # OpenNode
        - name: OPENNODE_API_KEY
          value: "" 
        # Lnbits
        - name: LNBITS_API_KEY
          value: "" 
      volumeMounts:
        - name: nostream-settings-volume
          mountPath: /home/node/.nostr
  volumes:
    - name: nostream-settings-volume
      configMap:
        name: nostream-settings
