name: push_migrations

on:
  schedule:
    - cron: '0 14 * * 1'

jobs:
  push_migrations:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: submodule
        run: git submodule update --init
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile.migrations
          push: true
          tags: ghcr.io/${{ github.actor }}/nostream_migrations:latest
