name: push_migrations

# on:
  # schedule:
    # - cron: '0 10 * * 5'
on: [push, pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: submodule
        run: git submodule update --init
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile.migrations
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nostream_migrations:latest
